### ISSUE TITLE
nothing happens...?!

### ISSUE THREAD

**Issue by martys-de** [inbasic/media-converter#10]
hi, i knew this addon before - but now as i installed the extra converter and muxer its not working..?! i use FF 4304 32bit 
when i start the converter i can click on any button nothing changes, click on settings, nothing happens, drag n drop a .mp4 on the field, red cross shows up and i cant drop it there...

ffmpeg is the latest 32bit...

what do i wrong..?

thanx, greetings marty

**Comment by martys-de** [comment]
just saw not a red cross but a black circle with a line in it... looks like sign "dont drop here"... ;)

**Comment by Zak-H** [comment]
I have the same Issue new firefox install, updated converter and downloaded 64bit FFmpeg pointe to correct location.
nothing happens.
when I drag a file in I see a red circle with a stripe through and no convertion command.
what went wrong??

Zak

**Comment by martys-de** [comment]
and i even tried with ffmpeg 32 and 64bit...
same prob... nothing happens - also the buttons are not working... 
just a blue frame changes but in the main window it stays the same...

**Comment by inbasic** [comment]
Seems like the UI has no access to the internal engine. To debug please follow:

1. Open Error Console (Ctrl + Shift + J)
2. Press the clear button
3. Disable and re-enable the extension
4. Now open the UI and see what error appears in the Console.

**Comment by inbasic** [comment]
Is this fixed on 0.7.1.1?
https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/versions

**Comment by martys-de** [comment]
with 7-11 it seems to work fine....! :-)

**Comment by martys-de** [comment]
better 0 1 7 1  :+1:

**Comment by Zak-H** [comment]
version 0.171 is working fine thanks

**Comment by ivanov007** [comment]
yes 0.1.7.1 upgrade work just fine
