### ISSUE TITLE
txt file keeps being created telling me to install ffmpeg even though I have, after every conversion

### ISSUE THREAD

**Issue by jimmyrustles** [inbasic/media-converter#11]
I got ffmpeg working, but after every conversion a .txt file appears saying "Error: For audio extraction form this video format, you need to install and configure FFmpeg (http://www.ffmpeg.org/download.html) from addon's settings." Also, an option to also delete the video file after a conversion would be great as well.

**Comment by inbasic** [comment]
I thing this error is from YouTube Video and Audio downloader extension, not from Media Converter.

Anyhow, open YouTube Video and Audio downloader's options page, From there you can point the extension to use your downloaded FFMpeg

**Comment by jimmyrustles** [comment]
I have pointed the extension to use the downloaded ffmpeg file, and the
media converter works fine, But I still get a txt file telling me to
download ffmpeg when I use it.
On 31 Jan 2016 5:35 pm, "InBasic" <notifications@github.com> wrote:
>
> I thing this error is from YouTube Video and Audio downloader extension,
not from Media Converter.
>
> Anyhow, open YouTube Video and Audio downloader's options page, From
there you can point the extension to use your downloaded FFMpeg

**Comment by inbasic** [comment]
So when you drop a media file into Media Converter's window you get this text log?

**Comment by jimmyrustles** [comment]
Sorry, I actually get this error popup when I just download the video with the Youtube Video and Audio Downloader, not when I drop it into the Media Converter and Muxer box.
![error](https://cloud.githubusercontent.com/assets/5096684/12735890/38554dc8-c997-11e5-97d4-ccdfe1351782.png)
and also this txt file gets created every time I download a video
![error1](https://cloud.githubusercontent.com/assets/5096684/12735872/198c89d8-c997-11e5-8fbf-9b8e0c682c20.PNG)

Media Converter and Muxer is working fine and I have pointed it to use the downloaded ffmpeg file.

![capture](https://cloud.githubusercontent.com/assets/5096684/12736027/7f1d5146-c998-11e5-87a8-b356a323058a.PNG)

**Comment by inbasic** [comment]
Okay so as I said, your problem is with YVAD, not Media converter. Head to YVAD's option page. There is a button to select FFmpeg location there as well. Set the location and the problem will be fixed.
