### ISSUE TITLE
Is it me, or is this thing broke

### ISSUE THREAD

**Issue by Kenca387** [inbasic/media-converter#17]
I added the media converter add on to firefox. That part worked ok. I clicked on the media converter button on the tool bar and the add on screen opened ok.

Then nothing worked. I had downloaded and unzipped ffmpeg. The browse button didn't work so I 
manually entered the path to ffmpeg.exe. the more setting button did not work.  the drag and drop 
function did not work. Please help.

**Comment by inbasic** [comment]
If the browse button doesnt work, it mean the extension cannot be initiated. Please follow these steps to track the bug.

1. Open error console (ctrl + shift + j)
2. Open add-ons manager
3. Disable and re-enable the extension
4. check the console for the newly generate error.

Please take an screenshot of the error and report it here

**Comment by lucashrossi** [comment]
The same problem here...
![screenmconverter](https://cloud.githubusercontent.com/assets/21231307/17953334/01fd7cf2-6a49-11e6-9cd4-f5b7c499ea5d.jpg)

**Comment by lucashrossi** [comment]
Hi, adding a new one lunching from the toolbar button:

FireFox 48.0.2 64bit

Thanks.

![mcerror](https://cloud.githubusercontent.com/assets/21231307/18072350/d94cefd8-6e33-11e6-8a65-4af184e123df.jpg)

**Comment by inbasic** [comment]
I am pushing 0.2.2 which hopefully fixes these kind of issues. Please reopen if you are still experiencing this after updating to 0.2.2
