### ISSUE TITLE
Error joining files: check the console

### ISSUE THREAD

**Issue by ekaris** [inbasic/media-converter#19]
Detailed error:
https://justpaste.it/yxir

**Comment by inbasic** [comment]
None of the input files have an extension and hence the Media Converter cannot decide a proper extension for you;
```
Unable to find a suitable output format for '/home/ech/Transferências/videoplayback-1
```

How these two input files are generated?

**Comment by ekaris** [comment]
They where downloaded using the youtube video and audio downloader firefox extension

**Comment by inbasic** [comment]
Can you reproduce this? I mean is there any video link that causes generation of two unknown format files?

**Comment by ekaris** [comment]
Yes, what I do is I right click on one of the list files from youtube video and audio downloader and use downloadthemall Firefox extension and it saves as "videoplayback" without extension

**Comment by inbasic** [comment]
Instead of right clicking, click on the download button on the left side of the item, then from the menu go with dTa.

**Comment by inbasic** [comment]
If you want to combine the already downloaded files, try to append them with proper extensions (.mp4, .m4a, ...)

**Comment by ekaris** [comment]
That's what iv'e done, I'm only using dta for the final step because clicking on any of the files doesn't do anything anymore..

**Comment by ekaris** [comment]
I discovered that this is in youtube itself on webm files they have now a generic name without extension, try to verify that yourself

**Comment by inbasic** [comment]
> because clicking on any of the files doesn't do anything anymore.

You mean clicking on last two buttons does nothing?
![screen shot 2016-10-11 at 10 38 32](https://cloud.githubusercontent.com/assets/351062/19261557/e1834ada-8f9e-11e6-81d3-90378e5820e1.png)

**Comment by ekaris** [comment]
I mean clicking on the files and download using normal firefox download doesn't do the download anymore, maybe because my profile is broken..

**Comment by ekaris** [comment]
I don't even have that integration of buttons of dta on the youtube video and audio downloader

**Comment by inbasic** [comment]
> I don't even have that integration of buttons of dta on the youtube video and audio downloader

As I said, you need to click on the download icon in the left side of each item for the menu to appear.

**Comment by inbasic** [comment]
> I mean clicking on the files and download using normal firefox download doesn't do the download anymore

To debug this, please open your Firefox Error Console (Ctrl + Shift + J). Now clear the console and left click on an item to see if a new error is generated in the console or not

**Comment by ekaris** [comment]
I got this from the console:
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Oct 11 2016 08:15:27 GMT+0100 (WEST)
Full Message: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFile.createUnique]
Full Stack: JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: get vFile :: line 996
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: onDownload :: line 1037
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: onFile :: line 993
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: getVideo/onDetect/< :: line 847
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 937
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 816
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 750main.js:996
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Oct 11 2016 08:15:31 GMT+0100 (WEST)
Full Message: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFile.createUnique]
Full Stack: JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: get vFile :: line 996
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: onDownload :: line 1037
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: onFile :: line 993
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://feca4b87-3be4-43da-a1b1-137c24220968-at-jetpack/lib/main.js :: getVideo/onDetect/< :: line 847
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 937
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 816
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 750****

**Comment by ekaris** [comment]
About the click on the left to reveal the buttons, that worked, its a bit hidden you know :p

**Comment by inbasic** [comment]
Are you sure the root folder for downloads is accessible?

**Comment by ekaris** [comment]
I'm running firefox on a Linux sandbox called firejail, it only allows Firefox access to the download folder (which has a different name on my language) so it should work

**Comment by inbasic** [comment]
Go to the options page, in the general tab, change "Select Download Folder" to custom mode and point the browse window to the folder and see if it helps

**Comment by ekaris** [comment]
Yes it now works, thanks! Worth to mention is that it was already on custom and the directory seemed right (maybe it didn't had the special character ê and was e) so i selected the same directory and it now works
