### ISSUE TITLE
Oops! The native client is crashed! [ERROR MESSAGE]

### ISSUE THREAD

**Issue by mrjoex3** [inbasic/media-converter#23]
Describing the steps that made it crash: 

- downloaded a youtube video in .mp4 format using a firefox addon called, "YouTube Video and Audio Downloader (Dev Edt.) 0.7.2

-Then used another addon called Media Converter and Muxer
-Drag the MP4 file into the Audio Extractor section, and crash!

**Comment by inbasic** [comment]
Go to the options page and make sure the path to FFmpeg is correct. Also make sure the FFmpeg executable is downloaded correctly. If not, overwrite it with a new version!
