### ISSUE TITLE
Chrome / Windows: script does not work correctly

### ISSUE THREAD

**Issue by aminco** [inbasic/media-converter#24]
Works great on Firefox.
Script does not test ok on Chrome (Windows).
See script output below; clicking "check the native integration" does not result in anything.  
---------
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
'REG' is not recognized as an internal or external command,
operable program or batch file.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
'REG' is not recognized as an internal or external command,
operable program or batch file.
.. Chrome Browser is supported
.. Firefox Browser is supported
.. Native Host is installed in C:\Users\Username\AppData\Local\com.add0n.node

>>> Application is ready to use <<<

Press any key to continue . . .  
-----

**Comment by inbasic** [comment]
That's weird! Since line 6 also throws error how come Firefox version works?

What do you get when you print "REG" in the command line tool (cmd.exe)? What is your Windows version?

**Comment by aminco** [comment]
When I type "REG" in the command line tool I get thi:
------
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\AudioLab>REG
'REG' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\AudioLab>
------

Also, I don't know if it's relevant, but FFmpeg is installed on this system
in a custom folder location (not the default).

**Comment by andy-portmen** [comment]
Okay then open the install.bat with a text editor and add the following to the top:
`set PATH="C:\Winnt;C:\Winnt\System32"`

Then execute the code one more time

**Comment by aminco** [comment]
Done that (as Administrator)... still same result -
I wonder - shouldn't it be "set PATH="C:\Windows\System32""?

------
D:\AudioLab\Downloads\windows>set PATH="C:\Winnt;C:\Winnt\System32"
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
'REG' is not recognized as an internal or external command,
operable program or batch file.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
'REG' is not recognized as an internal or external command,
operable program or batch file.
.. Chrome Browser is supported
.. Firefox Browser is supported
.. Native Host is installed in
C:\Users\AudioLab\AppData\Local\com.add0n.node


>>> Application is ready to use <<<


Press any key to continue . . .
------

Edo

**Comment by andy-portmen** [comment]
> as Administrator 

There is no need for administration permission.

> I wonder - shouldn't it be "set PATH="C:\Windows\System32""?

Try that too. You need to add the root directory for "reg.exe" application


https://stackoverflow.com/questions/2313512/reg-is-not-recognized-as-an-internal-or-external-command-operable-program-or

**Comment by aminco** [comment]
Uninstalling and re-installing with Winows32 path only resulted in 
---

D:\AudioLab\Downloads\windows>set PATH="C:\Windows\System32"
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
The operation completed successfully.
.. Chrome Browser is supported
.. Firefox Browser is supported
.. Native Host is installed in C:\Users\AudioLab\AppData\Local\com.add0n.node


>>> Application is ready to use <<<


Press any key to continue . . .
---
However, clicking on the Chrome extension's icon on top of the screen resulted in 
---
Oops! The native client is crashed!

Please open a bug report here and describe the steps to regenerate this crash.

To restart the converter click here
------

**Comment by andy-portmen** [comment]
Can you try with
`set PATH="%SYSTEM32%"`

If it works, I can update the `install.bat` file to prevent errors like this one.

> Oops! The native client is crashed!

It seems that the included NodeJS is not working on your Windows. First install NodeJS from https://nodejs.org/en/ and then try the extension.

**Comment by aminco** [comment]
With PATH="%SYSTEM32%", REG isn't found.
With path="C:\Windows\System32", the batch script completes with success
I installed Node with success
Uninstalled and reinstalled (with "C:\Windows\System32")

The extension still crashes on Chrome
The extension still works well on Firefox

Thanks for your help so far - I'm willing to do more testing.

**Comment by inbasic** [comment]
Please open Chrome in the logger mode and see what error you get when opening the converter window
https://developer.chrome.com/apps/nativeMessaging#native-messaging-debugging

**Comment by inbasic** [comment]
btw, are you using the WebExtension version in Firefox? or the JPM version?

https://addons.mozilla.org/en-US/firefox/addon/media-converter-and-muxer/
https://addons.mozilla.org/en-US/firefox/addon/media-conversion-tool/

**Comment by aminco** [comment]
Media Converter and Muxer 0.25

**Comment by aminco** [comment]
The log attached.

**Comment by inbasic** [comment]
You need to use GitHub page to attach a file

**Comment by aminco** [comment]
[chrome_debug.log](https://github.com/inbasic/media-converter/files/1366252/chrome_debug.log)

**Comment by inbasic** [comment]
There is no error in this log. Am I missing something? Have you tried opening the converter window while Chrome was logging? Did you get any error?

**Comment by aminco** [comment]
I did, I did get an error, but I'll repeat it.

**Comment by aminco** [comment]
I used Google's Sawbuck log viewer to capture the log. 
When clicking "Media Converter and Muxer" it opens with the error message "Oops! The native client is crashed!", and Sawbuck reports this:

INFORMATION	3500	3672	00:03:00-150		0	"%c action %ctabs/SET_ACTIVE_TAB %c@ 14:57:22.612", source: chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js (15131)
INFORMATION	3500	3672	00:03:00-150		0	"prev state", source: chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js (15136)
INFORMATION	3500	3672	00:03:00-152		0	"action    ", source: chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js (15137)
INFORMATION	3500	3672	00:03:00-152		0	"next state", source: chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js (15139)
INFORMATION	3500	3672	00:03:00-152		0	"console.groupEnd", source: chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/_vendor.js (15142)
INFORMATION	3500	3672	00:03:00-331		0	"Loaded once Sun Oct 08 2017 14:57:22 GMT+0300 (Jerusalem Daylight Time)", source: chrome-extension://ekfnbpgmmeahnnlpjibofkobpdkifapn/js/background.js (1)

**Comment by inbasic** [comment]
@aminco I don't see a single line with ID "ocnfecjfebnllnapjjoncgjnnkfmobjc" which is the ID of this extension.
