### ISSUE TITLE
Cannot open directory; number=-2, code=ENOENT

### ISSUE THREAD

**Issue by klaszlo** [inbasic/media-converter#25]
I'm on ubuntu linux 16.10, firefox 54.0. 
Had no problem with the client install, the gui starts, 
but when I open a file (drag and drop or open via the file selector), 
I get the error in the "output window" (lowest third part of the window).

Can I somehow enable a more detailed error output?
I tried to rename the file to not contain any special characters (including space), so it is just `ma.mp4` now, but still the same error.

**Comment by inbasic** [comment]
Use the settings tab and define a new temp directory that extension can read to and write from. Seems like the extension cannot open the root directory.

**Comment by klaszlo** [comment]
Makes no difference. 

I have set the two directories:

    Save files in: /home/user/Desktop
    Temporary Directory: /home/user/Desktop/down

When I restart the program (`Settings -> restart`), or restart the firefox itself.
The Temporary Directory resets to `/tmp`.

**Comment by inbasic** [comment]
True! It is fixed on 0.1.5. Please update and change the temp directory. This should fix the problem.
