### ISSUE TITLE
Feature request: dialog box "A new version is available"

### ISSUE THREAD

**Issue by Overc1ocker** [inbasic/media-converter#29]
I noticed that you added the dialog boxes! Thanks for that! I also noticed, that there was no indication of a new version of the native client before I re downloaded it, installed it, and the version number changed to 0.6.5. It would be cool if you added something like the screenshot, or even allowed the program to update itself automatically.
![screen shot 2017-11-16 at 6 16 16 pm](https://user-images.githubusercontent.com/31421349/32921230-c89b9584-cafa-11e7-98a9-94954c152031.png)

**Comment by inbasic** [comment]
Actually there is no need for that unless there is an important update in the NodeJS side. Updates that Andy is pushing to the NodeJS is usually to support new extensions and hence not affecting this extension.
