### ISSUE TITLE
Media converter can't find ffmpeg

### ISSUE THREAD

**Issue by Beckfield** [inbasic/media-converter#3]
OS: Linux Mint 17.1
Browser: Firefox 36.0
ffmpeg version 1.2.6-7:1.2.6-1~trusty1

I installed Media Converter and launched it. It reported that I needed ffmpeg, but the button to download and install it reported an error.  I installed ffmpeg from repository (ppa:jon-severinsson/ffmpeg).  Media Converter still can't find it, even after I used the Browse feature to locate it (/usr/bin).

At this point, Media Converter won't work because it doesn't recognize ffmpeg.  What can I do?

**Comment by inbasic** [comment]
Open Error console (Ctrl+Shift+J). First clear the console, then open Media Converter. Try to point the extension to /usr/bin/ffmpeg one more time and see if you get an error in the console.

**Comment by Beckfield** [comment]
Thanks for your response.
I followed your instructions.  No error appeared in the console when I selected ffmpeg.

**Comment by Beckfield** [comment]
Oh, I don't know if this will give a clue, but I was able to use ffmpeg in Terminal to do the merge I wanted to do.  So at least we know ffmpeg is installed correctly and is functional.

**Comment by inbasic** [comment]
How about when you open the converter window. Do you get any error?

**Comment by Beckfield** [comment]
No error in the console.  The UI has the red banner telling me I need ffmpeg.

When I hit the button to download/install ffmpeg, the error console gets the following:
Unknown property '-moz-box-shadow'.  Declaration dropped. combo:8:407
"DARLA notice: 501" combo:3:14721
Error in parsing value for 'word-break'.  Declaration dropped. combo:1:1656
Unknown property 'user-select'.  Declaration dropped. combo:1:3146
Unknown property '-moz-background-size'.  Declaration dropped. combo:1:3910
"caughterror:..-build-common-utils-use:2" combo:2:2039
"Exception in use tictac-autosuggest-compose,autosuggest-api-mail-endpoints callback: TypeError: c is undefined" combo:2:350
value is not a non-null object tabbrowser.xml:430:0
value is not a non-null object tabbrowser.xml:430:0
nsIJSON.encode is deprecated.  Please use JSON.stringify instead. ssl-observatory.js:601:0
value is not a non-null object tabbrowser.xml:430:0
value is not a non-null object tabbrowser.xml:430:0
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIChannel.contentType] DownloadCore.jsm:1725:0

**Comment by inbasic** [comment]
You can manually set FFmpeg path by opening "about:addons" in a new tab. Find the extension and open its preferences. Then use the browse button to locate FFmpeg. This will prevent the extension from showing the FFmpeg installation warning. However, I suspect this fixes the real problem.

**Comment by Beckfield** [comment]
Well, I had tried that earlier, but I just looked again.  It had the correct path, but I browsed and found it again.  No change.  The error still appears on launch.
Could it be a permissions issue?

**Comment by inbasic** [comment]
Maybe there is something wrong in the Linux built of the extension. To be honest, I never got a chance to check in on Linux. I'll keep this open. Let me know if you got anything new.

Another debugging method is to close all your Firefox windows. Then open just a single window and check the Error console. Maybe there is an error preventing the extension to initiate

**Comment by haytham-med** [comment]
hello the version in Jon Severinsson ppa is too old, and won't work, use a static linux build and link the executable ffmpeg in addon preferences, it worked..

**Comment by trinsic1** [comment]
Im having this problem on a windows 10 x64 platform and im pretty sure I have everything set correctly.
I downloaded the latest version of FFMPEG from Media Convert and Muxer, and I tried to download it manually and installed it, I set a path in my system variables and specified the path in Media Converted and Muxer, and also within the addon page and it still get the same error: "youtube video and audio downloader error for audio extraction from this video format, you need to install and configure FFmpeg"

I cant seem to think of anything else that I could do, FFMPEG works on the command line just fine, but firefox just throws an error dialog when I have it set to extract audio to a separate file in the plugin.

**Comment by inbasic** [comment]
> "youtube video and audio downloader error for audio extraction from this video format, you need to install and configure FFmpeg"

You are mixing Media Converter and YouTube video and audio downloader. These are different products. You need to set FFmpeg for each product in its options page.
