### ISSUE TITLE
basic UI information?

### ISSUE THREAD

**Issue by ikefer** [inbasic/media-converter#31]
I am on FF 58.0.2 and Media Converter 0.6.6. 
When I select settings and change path to file locations, how do I save those changes?
What about Local communication port 3002, do I leave it alone?
All the check marks for the settings are gray. If I change them they go green. Do they have to be green to be valid?
When I select a function, such as convert to MP3 and drag a source file, how do I say Go to start the conversion?
Thanks for this very powerful app but a little user guide would be very helpful.

**Comment by inbasic** [comment]
Thanks for the tips. I am going to update the descriptions in the next release. Please give it a try and reopen if the UI is not yet clear enough for new users.
