### ISSUE TITLE
User setting for locations & directories doesn't take. Reverts to default

### ISSUE THREAD

**Issue by stephensonp** [inbasic/media-converter#33]
In the Settings tab, I change the directory/path for: "FFmpeg Location," "Save Files In," and "Temporary Directory." The checkbox next to these settings turns green. So far so good. But when I use the converter (in this case the Audio Extractor), the _default_ directories are used, not the user-specified directories. When I go back to the settings tab, the user-specified directories are still there with green check boxes, even though those directories were not used by the Audio Extractor. If I close media-converter and re-open it, the default directories show in the Settings tab (user-specified settings are lost).

**Comment by inbasic** [comment]
You need to click on the green box for the extension to save your preferences. I am updating the descriptions and will highlight this too.
