### ISSUE TITLE
I get this error when trying to update the native client

### ISSUE THREAD

**Issue by jimmyrustles** [inbasic/media-converter#36]
![untitled](https://user-images.githubusercontent.com/5096684/46252257-c517f980-c4a9-11e8-9bd7-3108bcdcb7d3.png)

I've downloaded ffmpeg countless times via the update option in Settings and keep getting the error Oops! The native client just crashed! saying ffmpeg is broken or something, this is ridiculous.

**Comment by inbasic** [comment]
You get the error message that the NodeJS process is busy. Meaning a NodeJS executable is running and hence the system cannot overwrite it. Open the task manager and sort running processes by name. Then terminate all the NodeJS executables and then re-run the installer.

You may also try to restart your browser.

**Comment by jimmyrustles** [comment]
![untitled1](https://user-images.githubusercontent.com/5096684/46255390-b3e9df80-c4df-11e8-80c4-5f8bea3b56bf.png)
 I keep on getting this regardless if I hit update in Settings and get another ffmpeg for the hundredth time, I have ffmpeg on my Desktop. 
![untitled3](https://user-images.githubusercontent.com/5096684/46255444-691c9780-c4e0-11e8-8a90-f06abe432302.png)

**Comment by inbasic** [comment]
why FFMPeg path has "/" instead of "\"?

**Comment by inbasic** [comment]
btw, if your Desktop FFmpeg works, don't fo through the updating from the options page. We need to find out why it is not working.

**Comment by inbasic** [comment]
Copy `\` char using Ctrl+C and replace all the `/` with Ctrl+V.

**Comment by jimmyrustles** [comment]
Done, could I get a link to download ffmpeg please?

**Comment by inbasic** [comment]
https://ffmpeg.zeranoe.com/builds/

**Comment by inbasic** [comment]
screenshot of the settings tab? Also open the browser console with Ctrl + Shift + J and see if you get an error when opening the UI.

**Comment by jimmyrustles** [comment]
![untitled](https://user-images.githubusercontent.com/5096684/46257225-9a559180-c4f9-11e8-8573-9621d4e6b258.png)

This came up in the browser console (I don't know what any of this means)
'Attempt to set a forbidden header was denied: Connection 2237368739-lcs_client_bin.js:195:386'

**Comment by inbasic** [comment]
Everything looks good to me!

> This came up in the browser console 

this is not related to this extension.

Did you get an error in the browser console while doing a conversion? Where did you get the damaging alert?

btw, try to see if the downloaded FFMpeg is working or not. To do so, open a cmd.exe in the Desktop directory (you can hold shift key while requesting the usual context menu in the Desktop folder). Then type `ffmpeg.exe --version` in the cmd.exe window and press Enter. See if the output is okay or not

**Comment by jimmyrustles** [comment]
![untitled2](https://user-images.githubusercontent.com/5096684/46263826-c273dd80-c557-11e8-903e-2c6404c54908.png)

I'm guessing it's okay? 


![untitled3](https://user-images.githubusercontent.com/5096684/46263865-5b0a5d80-c558-11e8-820e-501b02779800.png)
This showed up in the browser console when I tried to do a conversion.

**Comment by inbasic** [comment]
> I'm guessing it's okay?

Yes, FFMpeg is just fine.

This is the first time I see this low level error in the console. At the moment I am not sure what the issue is. I need to somehow reproduce this. What is your Windows and Firefox versions?

**Comment by inbasic** [comment]
Let's do two more tests before I find the suitable platform to reproduce this bug

1. Download the node.exe file from https://nodejs.org/en/download/current/ (Windows Binary) and replace the one that is included in the package here: 
![screen shot 2018-10-02 at 12 28 17 pm](https://user-images.githubusercontent.com/351062/46339057-5362bb80-c621-11e8-8c28-8dae0a337641.png)

2. Try to use the extension in the Chrome browser and see if it can convert or not.

**Comment by jimmyrustles** [comment]
Installed it in Chrome and set the node.exe file in the right place and it
works fine in Chrome, just not in Firefox.
