### ISSUE TITLE
/tmp fills up

### ISSUE THREAD

**Issue by Isgar** [inbasic/media-converter#4]
Sometimes, if the video is too long or I download multiple files, /tmp gets clogged. There is no warning, no cleanup, and I see no option to change the conversion directory. The latter would solve the problem for me.

My /tmp is 2GB, and I don't want to enlarge it as I have only 4GB memory.

**Comment by inbasic** [comment]
Are you sure this is Media Converter's error? As far as I can remember, Media Converter does not use /tmp directory at all. This should be YouTube Video and Audie Downloader's bug, right?

**Comment by Isgar** [comment]
Maybe it is, my assumption was the conversion tool as the DASH files are placed into my Download folder, only the conversion seems to happen in /tmp

**Comment by Isgar** [comment]
I just found this: https://github.com/inbasic/iaextractor/issues/100
So I guess it is not related to Media Converter. Sorry for the noise.
