### ISSUE TITLE
Uninstalled Addon, how to uninstall the native client

### ISSUE THREAD

**Issue by zilexa** [inbasic/media-converter#43]
How do I completely undo all changes made to the system by installing the native client?

[Youtube Downloader Addon](https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx) had an install.sh and an uninstall.sh script, to install or completely remove its native client.

**Comment by inbasic** [comment]
Both extensions use the same native client (by Andy Portmen). The `uninstall.sh` script removes the entire native code.

**Comment by zilexa** [comment]
Great thanks!
