### ISSUE TITLE
sometimes have problem extracting mpeg-4 audio from mp4 videos

### ISSUE THREAD

**Issue by johnkneen** [inbasic/media-converter#7]
using media converter & muxer I tried to extract audio from mp4 video, & it did not work correctly, the mpeg-4 audio file was created but when I try to play, it did not work.

> after extracting an error box appeared saying "Check Error console for complete error report"
> I tried to open error console ctrl + shift + j but nothing happened.

> How do I open the Error Console to find the problem ???

> P.S. other MP4 videos I tried to extract the audio worked fine, just a few wont work.
> Thanks John

**Comment by inbasic** [comment]
To open error console go to Firefox menu -> Developer -> Browser Console

Also try to download the latest FFmpeg and replace it with the old one. Seems like some formats are not supported in your currently installed FFmpeg. You can check the error log for more info though.

**Comment by johnkneen** [comment]
Hi I downloaded the latest FFmpeg but it was not an executable file, this is it "ffmpeg-2.8.3.tar.bz2"

I changed the path from FFmpeg.exe to ffmpeg-2.8.3.tar.bz2, but it still wont work.

below is the error report using FFmpeg.exe downloaded on 12-6-15 .

I hope you can tell me whats going wrong.

Can you please give me the web page to download the latest FFmpeg.exe file.

Regards John




imconverter:ffmpeg version N-61599-gce9d3da Copyright (c) 2000-2014 the FFmpeg developers

  built on Mar 18 2014 22:01:44 with gcc 4.8.2 (GCC)

  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-zlib

  libavutil      52. 67.100 / 52. 67.100

  libavcodec     55. 52.102 / 55. 52.102

  libavformat    55. 34.101 / 55. 34.101

  libavdevice    55. 11.100 / 55. 11.100

  libavfilter     4.  3.100 /  4.  3.100

  libswscale      2.  5.101 /  2.  5.101

  libswresample   0. 18.100 /  0. 18.100

  libpostproc    52.  3.100 / 52.  3.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Public\Videos\16.9\House Of Pain - Jump Around.mp4':

  Metadata:

    major_brand     : isom

    minor_version   : 512

    compatible_brands: isomiso2avc1mp41

    encoder         : Lavf54.63.104

  Duration: 00:04:00.21, start: 0.200000, bitrate: 821 kb/s

    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 640x368 [SAR 1:1 DAR 40:23], 718 kb/s, SAR 51:50 DAR 204:115, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)

    Metadata:

      handler_name    : VideoHandler

    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)

    Metadata:

      handler_name    : SoundHandler

Output #0, ipod, to 'C:\Users\Public\Videos\16.9\House Of Pain - Jump Around.m4a':

  Metadata:

    major_brand     : isom

    minor_version   : 512

    compatible_brands: isomiso2avc1mp41

    encoder         : Lavf55.34.101

    Stream #0:0(eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, 96 kb/s (default)

    Metadata:

      handler_name    : SoundHandler

Stream mapping:

  Stream #0:1 -> #0:0 (copy)

Press [q] to stop, [?] for help

Assertion next_dts >= 0 failed at /home/kyle/software/ffmpeg/source/ffmpeg-git/libavformat/movenc.c:620



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

 ffmpeg.js:247

Date: Tue, 24 Nov 2015 00:15:08 -0800

**Comment by inbasic** [comment]
Download http://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-20151205-git-a16243a-win32-static.7z
Then extract it in a folder. FFmpeg.exe is inside the "bin" directory.
