### ISSUE TITLE
Muxer problems

### ISSUE THREAD

**Issue by Brutal-Moose** [inbasic/media-converter#8]
Hello, I am a novice with some things with computers. If you choose to help me, please give me the full instructions, with every step listed, or I may not be able to complete it. When I use the muxer/media converter Firefox Add-on, it will only work with M4As, whatever those are. It will not work with videos from youtube. It says those are DASH. I don't know what DASH means, but I cannot get the DASH files to work, after they have been fully downloaded.

**Comment by inbasic** [comment]
> It will not work with videos from youtube

Are you trying to download a Youtube video using Media Converter extension? 
Note that Media Converter is not a YouTube downloader.
